import { TableRow } from 'src/app/common/interfaces/table.interface';

export const allFiles: TableRow[] = [
  {
    id: 1,
    name: '1.jpg',
    author: 'Pushkin Alex',
    size: '54.5 MB',
    category: 'image',
    date: new Date(),
  },
  {
    id: 2,
    name: '2.png',
    author: 'Pushkin Alex',
    size: '5.5 MB',
    category: 'image',
    date: new Date(),
  },
  {
    id: 3,
    name: '1.kml',
    author: 'Pushkin Alex',
    size: '54.5 MB',
    category: 'map',
    date: new Date(),
  },
  {
    id: 4,
    name: '2.mp0',
    author: 'Pushkin Alex',
    size: '5.5 MB',
    category: 'map',
    date: new Date(),
  },
  {
    id: 5,
    name: '1.mp3',
    author: 'Pushkin Alex',
    size: '54.5 MB',
    category: 'movie',
    date: new Date(),
  },
  {
    id: 6,
    name: '2.mp3',
    author: 'Pushkin Alex',
    size: '5.5 MB',
    category: 'movie',
    date: new Date(),
  },
  {
    id: 7,
    name: '1.txt',
    author: 'Pushkin Alex',
    size: '54.5 MB',
    category: 'other',
    date: new Date(),
  },
];
